version: "3.9"

services:
    db:
      container_name: backend_postgres
      image: postgres:15.4
      restart: always
      env_file:
        - ./.env      
      volumes:
        - ./database/postgres:/var/lib/postgresql/data

    django:
      container_name: backend_django
      build:
        context: ./backend
        args:
          - DJANGO_SECRET="just_for_build_default_dummy_value"
          - DEBUG=""
          - POSTGRES_DB=""
          - POSTGRES_USER=""
          - POSTGRES_PASSWORD=""
          - POSTGRES_HOST=""
      restart: always
      ports:
        - 8000:8000
      env_file:
        - ./.env
      depends_on:
        - db